/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardDownload: typeof import('./components/CardDownload.vue')['default']
    CardFollow: typeof import('./components/CardFollow.vue')['default']
    CardLive: typeof import('./components/CardLive.vue')['default']
    CardSearch: typeof import('./components/CardSearch.vue')['default']
    DialogStreamer: typeof import('./components/DialogStreamer.vue')['default']
    DialogVideo: typeof import('./components/DialogVideo.vue')['default']
    DialogWrapper: typeof import('./components/DialogWrapper.vue')['default']
    DividerTitle: typeof import('./components/DividerTitle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    Explanation: typeof import('./components/Explanation.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputFilterOrAdd: typeof import('./components/InputFilterOrAdd.vue')['default']
    InputLayout: typeof import('./components/InputLayout.vue')['default']
    InputRow: typeof import('./components/InputRow.vue')['default']
    InputSearch: typeof import('./components/InputSearch.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NoData: typeof import('./components/NoData.vue')['default']
    Observer: typeof import('./components/Observer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
